name: Build All Modules
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Static code analysis
        run: ./gradlew :harmony-kotlin:ktlintCheck :harmony-kotlin:detekt

      - name: Build
        run: ./gradlew :harmony-kotlin:build --stacktrace

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
