name: deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

#      - name: Validate Gradle Wrapper
#        uses: gradle/wrapper-validation-action@v1

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish Library
        run: ./gradlew :harmony-kotlin:publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_HARMONY_NEXUS_USERNAME: ${{ secrets.HARMONY_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_HARMONY_NEXUS_PASSWORD: ${{ secrets.HARMONY_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_PASSPHRASE: ${{ secrets.PASSPHRASE }}

env:
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
